#!/usr/bin/env bash
# One command to get the backend up and usable: `./scripts/dev.sh`
#
# Idempotent. Safe to run when everything is already up — it will notice and skip
# rather than restart, so it doubles as "where is everything again?".
#
#   --reset       wipe the local DB and replay every migration from scratch
#   --no-user     skip seeding the local dev user
set -uo pipefail
cd "$(dirname "$0")/.."

RESET=0; SEED=1
for a in "$@"; do
  case "$a" in
    --reset) RESET=1 ;;
    --no-user) SEED=0 ;;
    *) echo "unknown flag: $a"; exit 2 ;;
  esac
done

DEV_EMAIL="${LW_DEV_EMAIL:-dev@lightweight.local}"
DEV_PASS="${LW_DEV_PASS:-devpassword123}"
PROJECT_REF="wbjnwhefotslkjxrvrgm"
API="http://127.0.0.1:54321"
# Fixed local demo key — published by Supabase, identical on every machine, not a secret.
ANON="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0"

say() { printf "\033[2m%s\033[0m\n" "$*"; }
ok()  { printf "  \033[32m✓\033[0m %s\n" "$*"; }
bad() { printf "  \033[31m✗\033[0m %s\n" "$*"; }

# ── 1. Docker ────────────────────────────────────────────────────────────────
# The VM has died mid-pull before, leaving the socket answering 500s while the
# UI still looks alive. Treat "not responding" as "needs a real restart".
say "[1/4] Docker"
if ! docker info >/dev/null 2>&1; then
  open -a Docker 2>/dev/null
  printf "  starting Docker"
  for _ in $(seq 1 60); do docker info >/dev/null 2>&1 && break; printf "."; sleep 2; done
  echo
fi
docker info >/dev/null 2>&1 && ok "engine up ($(docker version --format '{{.Server.Version}}' 2>/dev/null))" \
  || { bad "Docker will not start — quit Docker Desktop fully and rerun"; exit 1; }

# ── 2. Supabase ──────────────────────────────────────────────────────────────
say "[2/4] Supabase"
if [ "$RESET" = "1" ]; then
  supabase db reset >/dev/null 2>&1 && ok "database reset, all migrations replayed" || { bad "db reset failed"; exit 1; }
elif curl -sf -o /dev/null --max-time 3 "$API/auth/v1/settings" -H "apikey: $ANON"; then
  ok "already running"
else
  supabase start >/dev/null 2>&1 && ok "started" || { bad "supabase start failed — run it directly to see why"; exit 1; }
fi
MIGS=$(ls supabase/migrations/*.sql 2>/dev/null | wc -l | tr -d ' ')
ok "$MIGS migrations on disk"

# ── 3. Local dev user ────────────────────────────────────────────────────────
# Schema and edge-function work needs a real user_id: every table is default-deny
# under RLS, so with no user you cannot read or write a single row.
say "[3/4] Dev user"
if [ "$SEED" = "1" ]; then
  curl -s -X POST "$API/auth/v1/signup" -H "apikey: $ANON" -H "Content-Type: application/json" \
    -d "{\"email\":\"$DEV_EMAIL\",\"password\":\"$DEV_PASS\"}" >/dev/null 2>&1
  TOK=$(curl -s -X POST "$API/auth/v1/token?grant_type=password" -H "apikey: $ANON" \
    -H "Content-Type: application/json" -d "{\"email\":\"$DEV_EMAIL\",\"password\":\"$DEV_PASS\"}")
  UID_=$(printf '%s' "$TOK" | python3 -c "import sys,json;print(json.load(sys.stdin).get('user',{}).get('id',''))" 2>/dev/null)
  JWT=$(printf '%s' "$TOK" | python3 -c "import sys,json;print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null)
  if [ -n "$UID_" ]; then
    ok "$DEV_EMAIL"
    # Gitignored. Sourced by hand when poking at PostgREST or an edge function.
    cat > supabase/.dev-user.env <<EOF
# Regenerated by scripts/dev.sh. The JWT expires in an hour; rerun to refresh.
LW_DEV_EMAIL=$DEV_EMAIL
LW_DEV_PASS=$DEV_PASS
LW_DEV_USER_ID=$UID_
LW_DEV_JWT=$JWT
LW_ANON_KEY=$ANON
LW_API=$API
EOF
  else
    bad "could not sign in as $DEV_EMAIL"
  fi
else
  say "  skipped"
fi

# ── 4. Hosts ─────────────────────────────────────────────────────────────────
say "[4/4] Hosts"
LAN=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "-")
DEV=$(xcrun devicectl list devices 2>/dev/null | awk 'NR>2 && NF {print $0}' | grep -i connected | head -1)
[ -n "$DEV" ] && ok "device: $(echo "$DEV" | awk '{print $1, $2}') ($(echo "$DEV" | grep -oE '[0-9A-F-]{36}'))" \
             || say "  no device connected"

cat <<EOF

  DB            postgresql://postgres:postgres@127.0.0.1:54322/postgres
  API           $API
  Studio        http://127.0.0.1:54323
  Mail          http://127.0.0.1:54324

  Mac LAN       $LAN            (device host, if a build ever points at the local stack)
  Dev env       https://$PROJECT_REF.supabase.co   (what device builds actually use)

  Dev user      ${UID_:-–}
                creds + JWT in supabase/.dev-user.env

EOF
